# Generated by Django 2.1.1 on 2018-09-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='image',
        ),
        migrations.AddField(
            model_name='spell',
            name='class_list',
            field=models.CharField(default='All', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spell',
            name='casting_time',
            field=models.CharField(max_length=255),
        ),
    ]
